const tempPuzzle = [
  [
    { letter: "E", position: "1" },
    { letter: "P", position: "2" },
    { letter: "S", position: "3" },
    { letter: "O", position: "4" },
    { letter: "M", position: "5" },
    { letter: "S", position: "6" },
    { letter: "A", position: "7" },
    { letter: "L", position: "8" },
    { letter: "T", position: "9" },
    { letter: "S", position: "10" },
    { letter: null, position: null },
    { letter: "T", position: "11" },
    { letter: "S", position: "12" },
    { letter: "A", position: "13" },
    { letter: "R", position: "14" },
  ],
  [
    { letter: "R", position: "15" },
    { letter: "O", position: null },
    { letter: "C", position: null },
    { letter: "K", position: null },
    { letter: "E", position: null },
    { letter: "T", position: null },
    { letter: "C", position: null },
    { letter: "A", position: null },
    { letter: "R", position: null },
    { letter: "S", position: null },
    { letter: null, position: "1" },
    { letter: "B", position: "16" },
    { letter: "A", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
  ],
  [
    { letter: "N", position: "17" },
    { letter: "O", position: null },
    { letter: "R", position: null },
    { letter: "E", position: null },
    { letter: "L", position: null },
    { letter: "A", position: null },
    { letter: "T", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
    { letter: "N", position: null },
    { letter: null, position: null },
    { letter: "A", position: "18" },
    { letter: "F", position: null },
    { letter: "R", position: null },
    { letter: "O", position: null },
  ],
  [
    { letter: "N", position: "17" },
    { letter: "O", position: null },
    { letter: "R", position: null },
    { letter: "E", position: null },
    { letter: "L", position: null },
    { letter: "A", position: null },
    { letter: "T", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
    { letter: "N", position: null },
    { letter: null, position: null },
    { letter: "A", position: "18" },
    { letter: "F", position: null },
    { letter: "R", position: null },
    { letter: "O", position: null },
  ],
  [
    { letter: "N", position: "17" },
    { letter: "O", position: null },
    { letter: "R", position: null },
    { letter: "E", position: null },
    { letter: "L", position: null },
    { letter: "A", position: null },
    { letter: "T", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
    { letter: "N", position: null },
    { letter: null, position: null },
    { letter: "A", position: "18" },
    { letter: "F", position: null },
    { letter: "R", position: null },
    { letter: "O", position: null },
  ],
  [
    { letter: "N", position: "17" },
    { letter: "O", position: null },
    { letter: "R", position: null },
    { letter: "E", position: null },
    { letter: "L", position: null },
    { letter: "A", position: null },
    { letter: "T", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
    { letter: "N", position: null },
    { letter: null, position: null },
    { letter: "A", position: "18" },
    { letter: "F", position: null },
    { letter: "R", position: null },
    { letter: "O", position: null },
  ],
  [
    { letter: "N", position: "17" },
    { letter: "O", position: null },
    { letter: "R", position: null },
    { letter: "E", position: null },
    { letter: "L", position: null },
    { letter: "A", position: null },
    { letter: "T", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
    { letter: "N", position: null },
    { letter: null, position: null },
    { letter: "A", position: "18" },
    { letter: "F", position: null },
    { letter: "R", position: null },
    { letter: "O", position: null },
  ],
  [
    { letter: "N", position: "17" },
    { letter: "O", position: null },
    { letter: "R", position: null },
    { letter: "E", position: null },
    { letter: "L", position: null },
    { letter: "A", position: null },
    { letter: "T", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
    { letter: "N", position: null },
    { letter: null, position: null },
    { letter: "A", position: "18" },
    { letter: "F", position: null },
    { letter: "R", position: null },
    { letter: "O", position: null },
  ],
  [
    { letter: "N", position: "17" },
    { letter: "O", position: null },
    { letter: "R", position: null },
    { letter: "E", position: null },
    { letter: "L", position: null },
    { letter: "A", position: null },
    { letter: "T", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
    { letter: "N", position: null },
    { letter: null, position: null },
    { letter: "A", position: "18" },
    { letter: "F", position: null },
    { letter: "R", position: null },
    { letter: "O", position: null },
  ],
  [
    { letter: "N", position: "17" },
    { letter: "O", position: null },
    { letter: "R", position: null },
    { letter: "E", position: null },
    { letter: "L", position: null },
    { letter: "A", position: null },
    { letter: "T", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
    { letter: "N", position: null },
    { letter: null, position: null },
    { letter: "A", position: "18" },
    { letter: "F", position: null },
    { letter: "R", position: null },
    { letter: "O", position: null },
  ],
  [
    { letter: "N", position: "17" },
    { letter: "O", position: null },
    { letter: "R", position: null },
    { letter: "E", position: null },
    { letter: "L", position: null },
    { letter: "A", position: null },
    { letter: "T", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
    { letter: "N", position: null },
    { letter: null, position: null },
    { letter: "A", position: "18" },
    { letter: "F", position: null },
    { letter: "R", position: null },
    { letter: "O", position: null },
  ],
  [
    { letter: "N", position: "17" },
    { letter: "O", position: null },
    { letter: "R", position: null },
    { letter: "E", position: null },
    { letter: "L", position: null },
    { letter: "A", position: null },
    { letter: "T", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
    { letter: "N", position: null },
    { letter: null, position: null },
    { letter: "A", position: "18" },
    { letter: "F", position: null },
    { letter: "R", position: null },
    { letter: "O", position: null },
  ],
  [
    { letter: "N", position: "17" },
    { letter: "O", position: null },
    { letter: "R", position: null },
    { letter: "E", position: null },
    { letter: "L", position: null },
    { letter: "A", position: null },
    { letter: "T", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
    { letter: "N", position: null },
    { letter: null, position: null },
    { letter: "A", position: "18" },
    { letter: "F", position: null },
    { letter: "R", position: null },
    { letter: "O", position: null },
  ],
  [
    { letter: "N", position: "17" },
    { letter: "O", position: null },
    { letter: "R", position: null },
    { letter: "E", position: null },
    { letter: "L", position: null },
    { letter: "A", position: null },
    { letter: "T", position: null },
    { letter: "I", position: null },
    { letter: "O", position: null },
    { letter: "N", position: null },
    { letter: null, position: null },
    { letter: "A", position: "18" },
    { letter: "F", position: null },
    { letter: "R", position: null },
    { letter: "O", position: null },
  ],
];

module.exports = tempPuzzle;
